version: "3.9"
services:
  role:
    build: ./admin/
    ports:
      - "5002:5002"
  authentification:
    build: ./authentification/
    ports:
      - "5001:5001"
  player:
    build: ./player/
    ports:
      - "5000:5000"
  match:
    build: ./match/
    ports:
      - "5005:5005"

